version: "3.8"

services:
  go:
    image: c-mini-project
    build: # Use the Dockerfile from the current directory to build container.
      context: .
    container_name: c-go-app
    ports:
      - "8000:8000"
    depends_on:
      - "db"

  db:
    image: mysql # use latest version of mysql
    container_name: c-mysql # add a name for the container
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment: # add default values, see docs for more info.
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_PASSWORD: 12345678
      MYSQL_DATABASE: miniproject # create this database on startup
      MYSQL_TCP_PORT: 3306
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - "3306:3306"

volumes: # add volume to persist data.
  my-db:
